package com.webkul.mobikul.odoo.core.utils

enum class FailureStatus {
  EMPTY,
  API_FAIL,
  NO_INTERNET,
  ACCESS_DENIED,
  USER_UNAPPROVED,

  BAD_REQUEST,
  UNAUTHORISED_REQUEST,
  FORBIDDEN_RESOURCE,
  RESOURCE_NOT_FOUND,
  LARGE_PAYLOAD,

  SERVER_ERROR,
  UNSUPPORTED_REQUEST,
  BAD_GATEWAY,
  SERVER_MAINTENANCE,

  INCOMPLETE_ONBOARDING,
  OTHER
}